import type { ReadOnlyToolDescriptor } from '../dto/tool.dto';

export const READ_ONLY_TOOL_DESCRIPTORS: ReadOnlyToolDescriptor[] = [
  { name: 'get_dashboard_overview', description: '查询经营仪表盘总览。', requiredPermissions: ['reports.view'] },
  { name: 'list_orders', description: '查询订单列表（可按状态、客户、时间筛选）。', requiredPermissions: ['orders.view', 'orders.create'] },
  { name: 'get_order_detail', description: '按订单号查询订单详情。', requiredPermissions: ['orders.view', 'orders.create'] },
  { name: 'get_procurement_detail', description: '按采购单号查询采购详情。', requiredPermissions: ['procurement.manage'] },
  { name: 'get_inventory_overview', description: '查询库存总览。', requiredPermissions: ['inventory.view'] },
  { name: 'list_inventory_alerts', description: '查询低库存/预警商品。', requiredPermissions: ['inventory.view'] },
  { name: 'query_inventory_item', description: '按 SKU 或商品关键词查询库存明细。', requiredPermissions: ['inventory.view'] },
  { name: 'get_reports_overview', description: '查询报表概览与关键指标。', requiredPermissions: ['reports.view'] },
  { name: 'list_procurement_orders', description: '查询采购单列表。', requiredPermissions: ['procurement.manage'] },
  { name: 'list_procurement_suggestions', description: '查询补货建议。', requiredPermissions: ['procurement.manage'] },
  { name: 'get_finance_overview', description: '查询财务总览（应收/应付）。', requiredPermissions: ['finance.view'] },
  { name: 'get_receivable_detail', description: '按应收单号查询应收详情。', requiredPermissions: ['finance.view'] },
  { name: 'list_receivables', description: '查询应收列表。', requiredPermissions: ['finance.view'] },
  { name: 'list_receipt_records', description: '查询收款记录。', requiredPermissions: ['finance.view'] },
  { name: 'get_payable_detail', description: '按应付单号查询应付详情。', requiredPermissions: ['finance.view'] },
  { name: 'list_payables', description: '查询应付列表。', requiredPermissions: ['finance.view'] },
  { name: 'list_payment_records', description: '查询付款记录。', requiredPermissions: ['finance.view'] },
  { name: 'list_customers', description: '查询客户列表。', requiredPermissions: ['settings.master-data'] },
  { name: 'get_customer_detail', description: '按客户ID或关键词查询客户详情。', requiredPermissions: ['settings.master-data'] },
  { name: 'get_customer_summary', description: '查询客户概览指标。', requiredPermissions: ['settings.master-data'] },
  { name: 'list_audit_logs', description: '查询审计日志。', requiredPermissions: ['settings.access-control'] },
  { name: 'get_role_template_guide', description: '查询角色模板指南。', requiredPermissions: ['settings.access-control'] },
  { name: 'get_security_level_guide', description: '查询安全分级说明。', requiredPermissions: [] },
  { name: 'get_audit_definition', description: '查询审计口径定义。', requiredPermissions: ['settings.access-control'] },
  { name: 'get_report_definitions', description: '查询报表口径与指标定义。', requiredPermissions: [] },
  { name: 'get_api_catalog', description: '查询接口清单与权限映射。', requiredPermissions: [] },
  { name: 'get_database_table_detail', description: '查询数据库表结构细节。', requiredPermissions: [] },
  { name: 'get_access_overview', description: '查询权限、角色、账号总览。', requiredPermissions: ['settings.access-control'] },
  { name: 'get_master_data_overview', description: '查询基础资料总览（供应商/商品/仓库）。', requiredPermissions: ['settings.master-data'] },
  { name: 'get_password_policy', description: '查询密码策略。', requiredPermissions: [] },
  { name: 'get_password_security', description: '查询当前账号密码安全态势。', requiredPermissions: [] },
  { name: 'list_user_sessions', description: '查询当前账号会话列表。', requiredPermissions: [] },
  { name: 'get_arrival_detail', description: '按到货单号查询到货详情。', requiredPermissions: ['procurement.manage'] },
  { name: 'list_arrivals', description: '查询到货列表。', requiredPermissions: ['procurement.manage'] },
  { name: 'get_inbound_detail', description: '按入库单号查询入库详情。', requiredPermissions: ['procurement.manage'] },
  { name: 'list_inbounds', description: '查询入库列表。', requiredPermissions: ['procurement.manage'] },
  { name: 'get_shipment_detail', description: '按发货单号查询发货详情。', requiredPermissions: ['shipping.dispatch', 'orders.view', 'orders.create'] },
  { name: 'list_shipments', description: '查询发货列表。', requiredPermissions: ['shipping.dispatch', 'orders.view', 'orders.create'] },
  { name: 'list_system_notifications', description: '查询系统消息中心列表。', requiredPermissions: [] },
  { name: 'get_profile_memory', description: '查询当前长期画像记忆（Profile Memory）。', requiredPermissions: [] },
  { name: 'list_memory_facts', description: '查询记忆事实清单（Profile + Episodic 摘要）。', requiredPermissions: [] },
];
